#!/bin/sh -e
SEGMENTS="$HOME/.local/var/bar"
PROGS="$HOME/.local/bin/bar.d"
tmp="$(mktemp -d)"
pids="$tmp/pid"
files="$tmp/files"
n=50

cleanup() {
	if [ ! -f "$pids" ] || [ ! -f "$files" ]; then
		return 0
	fi
	while read -r pid; do
		if ps -o pid= -p "$pid"; then
			kill -s TERM "$pid"
		fi
	done < "$pids"
	while read -r file; do rm -f "$file"; done < "$files"
	rm -f "$pids"
	rm -f "$files"
}

trap 'cleanup' INT

mkdir -p "$SEGMENTS" "$PROGS"

if [ -f "$HOME/.config/bar" ]; then
	cat "$HOME/.config/bar"
else
	cat <<- EOF
		mail
		music
		memory
		date
		time
	EOF
fi | while read -r prg; do
	# each "base" program should hang until another invocation is needed
	# other programs will have to manage their own
	out="$SEGMENTS/$((n+=1))-$prg"
	touch "$out"
	echo "$out" >> "$files"
	while "$PROGS/$prg"; do
		:
	done | while read -r line; do
		# this second while loop is necessary
		# for processes that take time to complete
		echo "$line" > "$out"
	done & echo $! >> "$pids"
done

# each time one of the segment files is updated, concat the bar segments
while cat "${SEGMENTS:-"$HOME/.local/var/bar"}"/* |
	awk '/^$/ { next } !s { s=$0; next } { s = s " | " $0 } END { print s }'; do
		inotifywait -e CREATE,MOVED_FROM,DELETE,MODIFY "$SEGMENTS" >/dev/null 2>&1
	done

cleanup
